# Basic Information 
title: Di Zhang
position: Ph.D. Student
affiliation: UNC Charlotte
email: dzhang16 (at) uncc.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal academic
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=en&user=O-yNnmkAAAAJ
github_link: https://github.com/zhangdistephen
linkedin: https://www.linkedin.com/in/di-zhang-343b64146/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/download.png
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics
#google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
